name: Generate documentation
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Doxygen
        run: |
          sudo apt-get install -y doxygen
          doxygen Doxyfile
          mv html/jsonrpc_8lsl.html html/index.html
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.4.1
        with:
          folder: html
