name: Generate documentation
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Doxygen Action
        run: |
          sudo apt-get install -y doxygen
          ls
          doxygen Doxyfile
